services:
  - type: web
    name: lavalust
    env: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: DB_DRIVER
        value: pgsql
      - key: DB_SSLMODE
        value: require
